dist: trusty
sudo: false
language: cpp

os:
  - osx

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

cache:
  directories:
    - $HOME/.local

install:
  - if [[ "${COMPILER_VER}" != "" ]]; then export CXX=${CXX}-${COMPILER_VER}; fi
  - if [[ "${COMPILER_VER}" != "" ]]; then export CC=${CC}-${COMPILER_VER}; fi
  - if [[ "${COMPILER_VER}" != "" ]]; then export GCOV=gcov-${COMPILER_VER}; fi
  - if [[ "${USE_ASAN}" == "1" ]]; then export CXXFLAGS="-fsanitize=address -fno-omit-frame-pointer"; fi
  - if [[ "${USE_UBSAN}" == "1" ]]; then export CXXFLAGS="-fsanitize=undefined -fno-omit-frame-pointer"; fi
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew update && brew upgrade cmake
    fi

script:
  - ${CXX} --version
  - echo CXXFLAGS=${CXXFLAGS}
  - |
    if [[ "$BUILD_TYPE" == "Coverage" ]]; then
      ctest -S cmake/CI.CTestScript.cmake --output-on-failure -VV -DCTEST_SITE=Travis -DCTEST_BUILD_NAME="${TRAVIS_OS_NAME}-$BUILD_TYPE"
    else
      mkdir build && cd build && \
      cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE .. && \
      make -j4 && \
      ctest -VV .
    fi
after_success:
  - |
    if [[ "$BUILD_TYPE" == "Coverage" ]]; then
      bash <(curl -s https://codecov.io/bash) -X gcov || echo "Codecov did not collect coverage reports"
    fi